### ISSUE TITLE
Hide episode number if value is "null"

### ISSUE THREAD

**Issue by bilditup1** [Tautulli/Tautulli-Remote#133]
Sometimes, an episode (especially if it's a live TV episode) will have incomplete or missing data from the epg provider. In this case, the episode field is apparently empty/has a nonsense value in it. In the history section of the Tautulli app, this shows up as 'Enull'. This strikes me as inelegant. Might as well hide the episode value altogether in such case. The season number on these cases is also usually nonsense, using some default value like 1900; it might be worth looking into hiding this as well in such cases.

Would prefer not to leave this screenshot up long-term, once you've replied, would like to remove. 
[removed]

**Comment by TheMeanCanEHdian** [comment]
Go ahead and remove the screenshot.

**Comment by TheMeanCanEHdian** [comment]
I've made a fix for this that will be in the next release. When a live tv episode has no episode number it will display the air date instead of the season and episode numbers. This will also match what Tautulli is currently doing on the history page. Shows will valid episode numbers will still show things like `S2021 • E149`

**Comment by bilditup1** [comment]
Brilliant!

**Comment by TheMeanCanEHdian** [comment]
This is live in v2.11.2.
