### ISSUE TITLE
Unable to use numbers in TLD

### ISSUE THREAD

**Issue by asdfgugus** [Tautulli/Tautulli-Remote#178]
### Describe the bug

When you add a new Tautulli Server via QR-Code or manually, you can not use numbers in the top level domain. 
![Tautulli_Remote_bug_report](https://user-images.githubusercontent.com/96517369/183303022-0adaba59-1131-41ed-84fe-e960008e750d.png)

### Steps to Reproduce

1. Open Tautulli app settings
2. Click on "Register a Tautulli Server"
3. Insert either a Primary or Secondary Connection Address including numbers in the TLD. (http://tautulli.k8s)
4. Click on "Register" 

### Expected Behavior

I can add a Tautulli Server with numbers in the TLD.

### Tautulli Remote Version

v2.13.3

### Tautulli Version

v2.10.2

### Mobile Device

FP3+

### Mobile OS

Android 10

**Comment by TheMeanCanEHdian** [comment]
This is due to the 3rd party package being used to verify valid URLs. 

However, upon investigation into this validation I found that the [New gTLD Applicant Guidebook](https://newgtlds.icann.org/en/applicants/agb) specifies that "The ASCII label must consist entirely of letters (alphabetic characters a-z)". 
<details>
<summary>Full excerpt</summary>

```
The ASCII label must be a valid host name, as
specified in the technical standards DOD Internet
Host Table Specification (RFC 952), Requirements for
Internet Hosts — Application and Support (RFC
1123), and Application Techniques for Checking
and Transformation of Names (RFC 3696),
Internationalized Domain Names in Applications
(IDNA)(RFCs 5890-5894), and any updates thereto.

This includes the following:
1.2.1 The ASCII label must consist entirely of letters
(alphabetic characters a-z), or
Applicant Guidebook | version 2012-06-04
2-14
1.2.2 The label must be a valid IDNA A-label
(further restricted as described in Part II
below). 
```
</details>

As such I am not encouraged to add any bypasses to this check as it appears to be validating correctly.
